### ISSUE TITLE
Wrong store name resolving in connectToStores addon

### ISSUE THREAD

**Issue by kastigar** [yahoo/fluxible#163] opened 2015-05-15 09:58 UTC
On [this](https://github.com/yahoo/fluxible/blob/bd4eacc07eea6b7f4d4cb866eb6f1905f91ec0ab/addons/connectToStores.js#L46) line of `connectToStores` addon

```javascript
var storeName = store.name || store.storeName || store;
```

here is a wrong resolving order. It should be

```javascript
var storeName = store.storeName || store.name || store;
```

**Comment by mridgway** [comment] 2015-05-15 18:44
Duplicate of https://github.com/yahoo/fluxible/issues/143.

**Closed by mridgway** 2015-05-15 18:44 UTC
