### ISSUE TITLE
'Cannot call dispatch while another dispatch is executing' error

### ISSUE THREAD

**Issue by agrippanux** [yahoo/fluxible#134] opened 2015-04-17 16:55 UTC
I am upgrading from an older version of Fluxible, and am now seeing the error 'Cannot call dispatch while another dispatch is executing' when executing several actions together.  DispatcherContext says it should queue up an action if one is already in progress but the code throws an error if there is a currentAction.

```
/**
 * Dispatches a new action or queues it up if one is already in progress
 * @method dispatch
 * @param {String} actionName Name of the action to be dispatched
 * @param {Object} payload Parameters to describe the action
 * @throws {Error} if store has handler registered that does not exist
 */
DispatcherContext.prototype.dispatch = function dispatch(actionName, payload) {
    if (!actionName) {
        throw new Error('actionName parameter `' + actionName + '` is invalid.');
    }
    if (this.currentAction) {
        throw new Error('Cannot call dispatch while another dispatch is executing. Attempted to execute \'' + actionName + '\' but \'' + this.currentAction.name + '\' is already executing.');
    }
```

I was treating actions from components as fire-and-forget, but is there a specific pattern I should be following to make sure they don't execute over each other?

Forgive me if I should of posted this in the Dispatchr repo.

**Comment by Ambroos** [comment] 2015-04-18 19:32
I've noticed this too. The solution I went with is rewriting all my application logic, and putting more decision making in actions instead of in components. If you let dispatches happen while other dispatches are happening, you can end up with an endless loop, which is really not fun to fix or come across.

By rewriting all my actions as Promises (really fantastic things) and moving the executing-actions-in-respnose-to-actions-completing to actions, it's cleaned up my code a lot and it makes things a lot more manageable. Combined with `connectToStores` you should notice that your React components go from a mix of 'smart' components and 'dumb/pure' components to all being pretty dumb/pure. The major thing to avoid is using `executeAction` inside anything that responds to a store emitting a change. Don't execute actions in your `connectToStores` or `onChange` handler.

Actions from components should only be fired when they are the direct result of user interaction.

-------------------

One thing that might seem tempting but really shouldn't be done is delaying or queueing actions with `setTimeout` and variants. It's a lot more interesting in the long run to deal with this logic from inside actions.

**Comment by gpbl** [comment] 2015-04-19 21:47
I have a similar issue when running an action on `componentDidMount`, and it clashes with the `CHANGE_ROUTE_SUCCESS` action.

> Actions from components should only be fired when they are the direct result of user interaction.

In my case I'd like to execute an action fetching some data asynchronously only after the page has been rendered. My `FETCH_DATA_START` action is dispatched while the `navigateAction` is still executing. Any suggestion?

**Comment by Ambroos** [comment] 2015-04-20 08:16
I think they key is to introduce another that does both of them. It's easy with promises. Let's say it's `metaNavigateAction`. This action will first execute the `navigateAction` (which only does the navigate and no other loading of things), **then** execute your `fetchDataAction`.

The annoying thing about this is that you either need a big switch case in one of the actions to decide what to do depending on the route, or you somehow attach actions to components in a different way. I've chosen to attach static properties to my route handlers, example below.

Doing things on `componentDidMount` seems like a good idea at first, until you realise that `componentDidMount` is usually a direct result of a route change. But what if you have a navigate that stays in the same route but with different parameters. You start adding loading logic to `componentWillReceiveProps` too. And maybe to some other lifecycle methods. The end result is that you're checking if you should load something all the time, while you probably don't need to.

The idea behind Flux is that everything that happens happens through an action. So, it makes sense that the actions are in control of what to execute at what point, not your components.

-----------------

This is what happens in my project on a navigate. I use React-Router, so the flow may be different with Routr. Source samples: https://gist.github.com/Ambroos/7a22c22f7c745d1430a3

### Browser
1. React-Router receives a navigate command

2. I let React-Router render the Handler component right away. Stopping at this point would just render the right route with no data, or a loading indicator.

3. Fire off my `navigateAction` with the router state as payload, after the route handler rendering.

4. `navigateAction` goes through the route handlers currently active. All my route handlers have static properties that tell `navigateAction` what actions to execute.

5. These `navigateActions` all get the router state passed in as payload and can use the params/query values to decide what exactly to load. `navigateActions` have to return a Promise in my implementation, so they're just all fired off one after the other.

### Server

1. React-Router receives a navigate command

2. I fire off `navigateAction` right away. `navigateAction` will go through the static properties of the active route handlers and execute all their actions right away. All actions use promises, so it's easy to check when they're all done.

3. The actions attached to route handlers know what data to fetch from the router state they receive.

3. Once they're all done (`Promise.all` to the rescue), I expose the state, render the application to HTML and serve it.

-----------------------

The result of this? My React components really only display what's in the store, and they focus on that. My actions are completely responsible for making sure the stores contain the right state and data. Components are only responsible for firing off actions as a direct result of user interaction (clicking on something, scroll events, ...).

I've already gone through a few iterations, and I feel pretty good about this structure.

**Comment by mridgway** [comment] 2015-04-20 17:05
Hey guys, looks like there was a regression in the `executeAction` method where the `setImmediate` calls was removed. We will add that back in which should resolve this error that you're seeing.

**Comment by gpbl** [comment] 2015-04-20 17:15
Ah! thanks @mridgway for the update.

BTW @Ambroos suggestions are always valid :+1: I'm following a similar structure in my code as well.

**Comment by mridgway** [comment] 2015-04-23 00:35
This has been fixed with #141, although there will be a warning about circular dispatches still.

**Closed by mridgway** 2015-04-23 00:35 UTC

**Comment by agrippanux** [comment] 2015-04-23 00:39
Getting this error when using 0.4.4:

TypeError: Cannot read property 'currentAction' of null
    at FluxContext.executeAction (/Users/darren/code/massdrop-react/node_modules/fluxible/lib/FluxibleContext.js:118:29)

When I do this:

var context = app.createContext();
context.executeAction(navigateAction…)

Error is here in FluxibleContext:

    if (process.env.NODE_ENV !== 'production') {
        if (this._dispatcher.currentAction) {

Commenting out the entire process.env.NODE_ENV production check works.

Should I be instantiating the context differently before calling executeAction?

-- 
darren

On April 22, 2015 at 5:35:39 PM, Michael Ridgway (notifications@github.com) wrote:

Closed #134.

**Comment by mridgway** [comment] 2015-04-23 00:40
Nope, looks like a bug. Will fix immediately.

**Comment by mridgway** [comment] 2015-04-23 00:45
Please try 0.4.5.

**Comment by agrippanux** [comment] 2015-04-23 00:48
works great, thanks :)
